[package]
version = "0.1.0"
name = "state-proof-circuit"
edition = "2021"

[dependencies]
valence-coprocessor = { path = "../../../../../core", default-features = false }
valence-coprocessor-ethereum = { path = "../../../", default-features = false, features = ["circuit"] }
sp1-zkvm = "4.2.0"
